Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('MRVL8686', src, depend = ['RT_USING_LWIP', 'RT_USING_WIFI'], CPPPATH = CPPPATH)

Return('group')
