Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')
src += Glob('./real/*.c')

SrcRemove(src, 'polyphase.c')
if rtconfig.PLATFORM == 'iar':
	src += ['./real/arm/asmmisc_iar.s', './real/arm/asmpoly_thumb2_iar.s']
if rtconfig.PLATFORM == 'armcc':
	src += ['./real/arm/asmmisc.s', './real/arm/asmpoly_thumb2.s']
if rtconfig.PLATFORM == 'gcc':
	Return('')

cwd     = GetCurrentDir()

CPPPATH = [cwd + '/pub']


group = DefineGroup('mp3', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
